question_data = [
    {"category": "Entertainment: Video Games",
     "type": "boolean",
     "difficulty": "easy",
     "question": "The song \"Megalovania\" by Toby Fox made its third appearence in the "
                 "2015 RPG \"Undertale\".",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "General Knowledge",
     "type": "boolean",
     "difficulty": "easy",
     "question": "French is an official language in Canada.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "History",
     "type": "boolean",
     "difficulty": "easy",
     "question": "The Spitfire originated from a racing plane.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "General Knowledge",
     "type": "boolean",
     "difficulty": "easy",
     "question": "Nutella is produced by the German company Ferrero.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Japanese Anime & Manga",
     "type": "boolean",
     "difficulty": "easy",
     "question": "In the \"Melancholy of Haruhi Suzumiya\" series, the narrator goes by the nickname Kyon.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Film",
     "type": "boolean",
     "difficulty": "easy",
     "question": "In the movie The Revenant, DiCaprio's character hunts down the killer of his son.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Politics",
     "type": "boolean",
     "difficulty": "easy",
     "question": "One of Barack Obama's United States presidential campaign slogan's was "
                 "\"Yes We Can\".",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "easy",
     "question": "Linux was first created as an alternative to Windows XP.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Television",
     "type": "boolean",
     "difficulty": "easy",
     "question": "In \"Doctor Who\", the Doctor gets his TARDIS by stealing it.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Geography",
     "type": "boolean",
     "difficulty": "easy",
     "question": "Hungary is the only country in the world beginning with H.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]}
]
